"""Lexical search and hybrid retrieval against real PostgreSQL.

The tsvector column is generated by PostgreSQL and matched with ``@@`` through a
GIN index, so none of this can be observed without a real database. Embeddings
use a stand-in provider; what is under test is the SQL and the fusion around it.
"""

from __future__ import annotations

import uuid
from collections.abc import Iterator

import pytest
from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

import app.services.retrieval as retrieval_module
from app.core.config import get_settings
from app.db.session import get_engine, get_session_factory
from app.models.embedding import EMBEDDING_DIMENSIONS, ChunkEmbedding
from app.models.repository import IndexingStatus, Repository, RepositoryVisibility
from app.models.source import ChunkType, CodeChunk, SourceFile
from app.repositories import lexical_repo
from app.services.lexical import build_tsquery, chunk_lexical_fields, query_terms
from app.services.retrieval import RetrievalStrength, retrieve

pytestmark = pytest.mark.integration

MODEL = "fake-embedder"


def _database_available() -> bool:
    try:
        with get_engine().connect() as connection:
            connection.execute(text("SELECT 1"))
    except SQLAlchemyError:
        return False
    return True


@pytest.fixture(scope="module", autouse=True)
def require_database() -> None:
    if not _database_available():
        pytest.skip("No reachable database at DATABASE_URL")


@pytest.fixture(autouse=True)
def clean_tables() -> Iterator[None]:
    def wipe() -> None:
        with get_session_factory()() as session:
            for table in ("chunk_embeddings", "code_chunks", "files", "repositories"):
                session.execute(text(f"DELETE FROM {table}"))
            session.commit()

    wipe()
    yield
    wipe()


@pytest.fixture
def db() -> Iterator[Session]:
    session = get_session_factory()()
    yield session
    session.rollback()
    session.close()


def _vector(direction: int) -> list[float]:
    """Unit vector along one axis: cosine similarity is 1 on the axis, 0 off it."""
    vector = [0.0] * EMBEDDING_DIMENSIONS
    vector[direction] = 1.0
    return vector


@pytest.fixture
def repository(db: Session) -> Repository:
    repo = Repository(
        owner="acme",
        name="retail",
        provider="github",
        default_branch="main",
        visibility=RepositoryVisibility.PUBLIC,
        indexing_status=IndexingStatus.INDEXED,
        embedding_model=MODEL,
    )
    db.add(repo)
    db.commit()
    return repo


def _add_chunk(
    db: Session,
    repository: Repository,
    *,
    path: str,
    symbol: str | None,
    content: str,
    direction: int,
    language: str = "python",
    with_lexical: bool = True,
) -> CodeChunk:
    source_file = (
        db.query(SourceFile).filter_by(repository_id=repository.id, path=path).one_or_none()
    )
    if source_file is None:
        source_file = SourceFile(
            repository_id=repository.id,
            path=path,
            blob_sha=uuid.uuid4().hex[:40],
            size_bytes=len(content),
            line_count=content.count("\n") + 1,
            language=language,
            content=content,
            is_parsed=True,
        )
        db.add(source_file)
        db.flush()

    names, body = (
        chunk_lexical_fields(file_path=path, symbol=symbol, parent_symbol=None, content=content)
        if with_lexical
        else ("", "")
    )
    chunk = CodeChunk(
        file_id=source_file.id,
        repository_id=repository.id,
        chunk_type=ChunkType.FUNCTION,
        symbol=symbol,
        start_line=1,
        end_line=content.count("\n") + 1,
        start_byte=0,
        end_byte=len(content),
        language=language,
        content=content,
        lexical_names=names,
        lexical_body=body,
    )
    db.add(chunk)
    db.flush()
    db.add(
        ChunkEmbedding(
            chunk_id=chunk.id,
            repository_id=repository.id,
            provider="fake",
            model=MODEL,
            dimensions=EMBEDDING_DIMENSIONS,
            embedding=_vector(direction),
        )
    )
    db.commit()
    return chunk


def _seed_retail(db: Session, repository: Repository) -> dict[str, CodeChunk]:
    chunks = {
        "get_db": _add_chunk(
            db,
            repository,
            path="backend/api.py",
            symbol="get_db",
            content="def get_db():\n    conn = sqlite3.connect(DB_PATH)\n    return conn\n",
            direction=1,
        ),
        "commercial": _add_chunk(
            db,
            repository,
            path="backend/api.py",
            symbol="get_commercial_data",
            content=(
                "@app.get('/analytics/commercial')\n"
                "def get_commercial_data():\n"
                "    conn = get_db()\n"
            ),
            direction=2,
        ),
        "operations_ui": _add_chunk(
            db,
            repository,
            path="web/src/App.jsx",
            symbol="Operations",
            content=(
                "const Operations = () => {\n"
                "  const categories = useMemo(() => keys, [data]);\n"
                "};\n"
            ),
            direction=3,
            language="jsx",
        ),
    }
    for index in range(10):
        _add_chunk(
            db,
            repository,
            path=f"backend/generic_{index}.py",
            symbol=f"helper_{index}",
            content=f"def helper_{index}(value):\n    return value * {index}\n",
            direction=10 + index,
        )
    return chunks


class TestLexicalRepository:
    def test_finds_a_camel_case_identifier(self, db: Session, repository: Repository) -> None:
        chunks = _seed_retail(db, repository)

        hits = lexical_repo.search_chunks(
            db, repository_id=repository.id, tsquery=build_tsquery(["usememo"]), limit=10
        )

        assert [hit.chunk_id for hit in hits] == [chunks["operations_ui"].id]
        assert "usememo" in hits[0].terms

    def test_a_chunk_named_after_the_term_outranks_one_that_mentions_it(
        self, db: Session, repository: Repository
    ) -> None:
        chunks = _seed_retail(db, repository)

        hits = lexical_repo.search_chunks(
            db, repository_id=repository.id, tsquery=build_tsquery(["getdb"]), limit=10
        )

        assert [hit.chunk_id for hit in hits] == [chunks["get_db"].id, chunks["commercial"].id]

    def test_document_frequencies_are_counted_per_repository(
        self, db: Session, repository: Repository
    ) -> None:
        _seed_retail(db, repository)

        stats, available = lexical_repo.term_statistics(
            db, repository.id, ("getdb", "helper", "stripe")
        )

        assert available
        assert stats.total_chunks == 13
        assert stats.document_frequency == {"getdb": 2, "helper": 10, "stripe": 0}

    def test_an_index_without_lexical_fields_is_reported_not_silently_empty(
        self, db: Session, repository: Repository
    ) -> None:
        _add_chunk(
            db,
            repository,
            path="a.py",
            symbol="f",
            content="def f(): ...",
            direction=1,
            with_lexical=False,
        )

        _, available = lexical_repo.term_statistics(db, repository.id, ("f",))

        assert available is False


class _FakeProvider:
    model = MODEL
    dimensions = EMBEDDING_DIMENSIONS

    def __init__(self, direction: int) -> None:
        self._direction = direction

    def embed_text(self, text: str, *, kind: object) -> list[float]:
        return _vector(self._direction)


class TestHybridRetrieve:
    def test_exact_symbol_wins_when_the_query_vector_points_elsewhere(
        self, db: Session, repository: Repository, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        chunks = _seed_retail(db, repository)
        # The question's vector is closest to an unrelated helper.
        monkeypatch.setattr(retrieval_module, "get_embedding_provider", lambda s: _FakeProvider(12))

        result = retrieve(
            db, repository=repository, query="Where is get_db defined?", settings=get_settings()
        )

        assert result.sources[0].chunk_id == str(chunks["get_db"].id)
        assert result.sources[0].exact_match == "symbol"
        assert result.semantic[0].symbol == "helper_2"
        assert result.lexical_available
        assert result.strength is RetrievalStrength.USEFUL

    def test_lexical_candidates_carry_their_real_semantic_score(
        self, db: Session, repository: Repository, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        chunks = _seed_retail(db, repository)
        monkeypatch.setattr(retrieval_module, "get_embedding_provider", lambda s: _FakeProvider(3))

        result = retrieve(
            db, repository=repository, query="Where is useMemo used?", settings=get_settings()
        )

        top = result.sources[0]
        assert top.chunk_id == str(chunks["operations_ui"].id)
        assert top.score == pytest.approx(1.0)
        assert top.exact_match == "identifier"

    def test_unsupported_vocabulary_matches_nothing_lexically(
        self, db: Session, repository: Repository, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        _seed_retail(db, repository)
        monkeypatch.setattr(
            retrieval_module, "get_embedding_provider", lambda s: _FakeProvider(900)
        )

        result = retrieve(
            db,
            repository=repository,
            query="Where is Stripe webhook processing implemented?",
            settings=get_settings(),
        )

        assert result.lexical == []
        assert query_terms("Stripe webhook").terms == ("stripe", "webhook")
        assert result.strength is RetrievalStrength.NONE
